"""Database layer for STA Starship Simulator."""

from .db import init_db, get_session, get_db, engine, async_engine
from .schema import (
    CharacterRecord,
    StarshipRecord,
    EncounterRecord,
    CombatLogRecord,
    CampaignRecord,
    CampaignPlayerRecord,
    CampaignShipRecord,
    SceneRecord,
    NPCRecord,
    CampaignNPCRecord,
    SceneNPCRecord,
    CharacterTraitRecord,
    PersonnelEncounterRecord,
    SceneParticipantRecord,
    SceneShipRecord,
)
from .vtt_schema import (
    VTTCharacterRecord,
    VTTShipRecord,
    UniverseLibraryRecord,
    UniverseItemRecord,
    TraitRecord,
    TalentRecord,
    WeaponRecord,
    LogEntryRecord,
)

__all__ = [
    "init_db",
    "get_session",
    "engine",
    "CharacterRecord",
    "StarshipRecord",
    "EncounterRecord",
    "CombatLogRecord",
    "CampaignRecord",
    "CampaignPlayerRecord",
    "CampaignShipRecord",
    "SceneRecord",
    "NPCRecord",
    "CampaignNPCRecord",
    "SceneNPCRecord",
    "CharacterTraitRecord",
    "PersonnelEncounterRecord",
    "SceneParticipantRecord",
    "SceneShipRecord",
    "VTTCharacterRecord",
    "VTTShipRecord",
    "UniverseLibraryRecord",
    "UniverseItemRecord",
    "TraitRecord",
    "TalentRecord",
    "WeaponRecord",
    "LogEntryRecord",
]
